var_parameters = {
	"QFX"		: { "compute_mode":1, "shiftday":-1 },
	"LH"		: { "compute_mode":1, "shiftday":0  },
	"ATH2"		: { "compute_mode":1, "shiftday":-1 },
	"WSAVG"  	: { "compute_mode":1, "shiftday":0 },
	"WSAVG"  	: { "compute_mode":1, "shiftday":0 },
	"WSMIN"  	: { "compute_mode":9, "shiftday":1 },
	"WSMAX"  	: { "compute_mode":8, "shiftday":1 },
	"XFCOV"  	: { "compute_mode":1, "shiftday":0 },
	"XQRCHRG"  	: { "compute_mode":1, "shiftday":0 },
	"XRNOF"  	: { "compute_mode":1, "shiftday":0 },
	"XRSAT"  	: { "compute_mode":1, "shiftday":0 },
	"XRDRN"  	: { "compute_mode":1, "shiftday":0 },
	"XRBAS"  	: { "compute_mode":1, "shiftday":0 },
	"XRSUR"  	: { "compute_mode":1, "shiftday":0 },
	"XTAUX"  	: { "compute_mode":1, "shiftday":0 },
	"XTAUY"  	: { "compute_mode":1, "shiftday":0 },
	"XUPTKW"  	: { "compute_mode":1, "shiftday":0 },
	"XRTWS"  	: { "compute_mode":1, "shiftday":0 },
	"XSWDEPTH"  : { "compute_mode":1, "shiftday":0 },
	"AGFX"  	: { "compute_mode":1, "shiftday":0 },
	"CANWAT"  	: { "compute_mode":1, "shiftday":0 },
	"ACSNOW"  	: { "compute_mode":1, "shiftday":0 },
	"AGFX"  	: { "compute_mode":1, "shiftday":0 },
	"ARBAS"  	: { "compute_mode":1, "shiftday":0 },
	"ATSK"  	: { "compute_mode":1, "shiftday":0 },
	"PRMIN" 	: { "compute_mode":9, "shiftday":1 },
	"PRMAX" 	: { "compute_mode":8, "shiftday":1 },
	"PRAVG" 	: { "compute_mode":6, "shiftday":1 },
	"AOUTFLOW" 	: { "compute_mode":1, "shiftday":0 },
	"XSABVG" 	: { "compute_mode":1, "shiftday":0 },
	"ARNOF" 	: { "compute_mode":1, "shiftday":0 },
	"ARSUR" 	: { "compute_mode":1, "shiftday":0 },
	"SNOWNC"	: { "compute_mode":1, "shiftday":0 },
	"SNOWC"		: { "compute_mode":1, "shiftday":0 },
	"EMISS"		: { "compute_mode":1, "shiftday":0 },
	"UQg"		: { "compute_mode":1, "shiftday":0 },
	"VQg"		: { "compute_mode":1, "shiftday":0 },
	"XSMIg"		: { "compute_mode":1, "shiftday":0 },
	"XSMLg"		: { "compute_mode":1, "shiftday":0 },
	"XSMTg"		: { "compute_mode":1, "shiftday":0 },
	"CAPE"		: { "compute_mode":1, "shiftday":0 },
	"CAPE1"		: { "compute_mode":1, "shiftday":0 },
	"CAPE2"		: { "compute_mode":1, "shiftday":0 },
	"CAPE3"		: { "compute_mode":1, "shiftday":0 },
	"AT2M"		: { "compute_mode":1, "shiftday":0 },
	"T2M"		: { "compute_mode":1, "shiftday":0 },
	"SST"		: { "compute_mode":1, "shiftday":0 },
	"XTSS"		: { "compute_mode":1, "shiftday":0 },
	"T2"		: { "compute_mode":1, "shiftday":0 },
	"AU2M"		: { "compute_mode":1, "shiftday":0 },
	"AV2M"		: { "compute_mode":1, "shiftday":0 },
	"AQ2M"		: { "compute_mode":1, "shiftday":0 },
	"T2MAX"		: { "compute_mode":8, "shiftday": 1 },
	"T2MIN"		: { "compute_mode":9, "shiftday": 1 },
	"RAINC"		: { "compute_mode":5, "shiftday": 0 },
	"RAINNC"	: { "compute_mode":5, "shiftday": 0 },
	"PCT"		: { "compute_mode":11, "shiftday": 0 },
	"CDD"		: { "compute_mode":12, "shiftday": 0 },
	"RAINYDAYS"	: { "compute_mode":13, "shiftday": 0 },
	"R10"	    : { "compute_mode":13, "shiftday": 0 },
	"R5D"	    : { "compute_mode":14, "shiftday": 0 },
	"SDII"	    : { "compute_mode":15, "shiftday": 0 },
	"R95T"	    : { "compute_mode":16, "shiftday": 0 },
	"AU10"		: { "compute_mode":1, "shiftday":-1 },
	"AV10"		: { "compute_mode":1, "shiftday":-1 },
	"AQ2M"		: { "compute_mode":1, "shiftday":-1 },
	"ASWUPT"	: { "compute_mode":1, "shiftday":0 },
	"ASWUPTC"	: { "compute_mode":1, "shiftday":0 },
	"ASWDNT"	: { "compute_mode":1, "shiftday":0 },
	"ASWDNS"	: { "compute_mode":1, "shiftday":0 },
	"ASWDNSC"	: { "compute_mode":1, "shiftday":0 },
	"ASWUPS"	: { "compute_mode":1, "shiftday":0 },
	"ASWUPSC"	: { "compute_mode":1, "shiftday":0 },
	"ALWUPT"	: { "compute_mode":1, "shiftday":0 },
	"ALWUPTC"	: { "compute_mode":1, "shiftday":0 },
	"ALWDNS"	: { "compute_mode":1, "shiftday":0 },
	"ALWDNSC"	: { "compute_mode":1, "shiftday":0 },
	"ALWUPS"	: { "compute_mode":1, "shiftday":0 },
	"ALWUPSC"	: { "compute_mode":1, "shiftday":0 },
	"TCWPC"		: { "compute_mode":1, "shiftday":-1 },
	"TCWPR"		: { "compute_mode":1, "shiftday":-1 },
	"TCWPI"		: { "compute_mode":1, "shiftday":-1 },
	"CLDFRA"	: { "compute_mode":1, "shiftday":-1 },
	"CLDFRAg"	: { "compute_mode":1, "shiftday":-1 },
	"CLDFRApbl"	: { "compute_mode":1, "shiftday":-1 },
	"CLDCNVg"	: { "compute_mode":1, "shiftday":-1 },
	"CLDSCUg"	: { "compute_mode":1, "shiftday":-1 },
	"XSWI"		: { "compute_mode":1, "shiftday":-1 },
	"PBLH"		: { "compute_mode":1, "shiftday":-1 },
	"TKES"		: { "compute_mode":1, "shiftday":-1 },
	"UST"		: { "compute_mode":1, "shiftday":-1 },
	"WCSTAR"	: { "compute_mode":1, "shiftday":-1 },
	"BR"		: { "compute_mode":1, "shiftday":-1 },
	"POTEVP"	: { "compute_mode":5, "shiftday": 0 },
	"SFROFF"	: { "compute_mode":5, "shiftday": 0 },
	"UDROFF"	: { "compute_mode":5, "shiftday": 0 },
	"SNOW"		: { "compute_mode":1, "shiftday":-1 },
	"SNOWFALL"	: { "compute_mode":12,"shiftday":-1 },
	"SNOWH"		: { "compute_mode":1, "shiftday":-1 },
	"XTSS"		: { "compute_mode":1, "shiftday":-1 },
	"XOUTFLOW"	: { "compute_mode":1, "shiftday":-1 },
	"XPARSUN"	: { "compute_mode":1, "shiftday":-1 },
	"XPARSHA"	: { "compute_mode":1, "shiftday":-1 },
	"AHFX"		: { "compute_mode":1, "shiftday":0 },
	"ALFX"		: { "compute_mode":1, "shiftday":0 },
	"XETR"		: { "compute_mode":1, "shiftday":-1 },
	"XFEVPL"	: { "compute_mode":1, "shiftday":-1 },
	"XFEVPG"	: { "compute_mode":1, "shiftday":-1 },
	"XZWT"		: { "compute_mode":1, "shiftday":-1 }, 
	"PS"   		: { "compute_mode":1, "shiftday":0 }, 
	"PSL"  		: { "compute_mode":1, "shiftday":0 }, 
	"H"  		: { "compute_mode":1, "shiftday":0 }, 
	"TPW"		: { "compute_mode":1, "shiftday":-1 }, 
	"AUQV"		: { "compute_mode":1, "shiftday":-1 }, 
	"AVQV"		: { "compute_mode":1, "shiftday":-1 }, 
	"QVAPOR"			: { "compute_mode":1, "shiftday":0 }, 
	"QCLOUD"			: { "compute_mode":1, "shiftday":0 }, 
	"QRAIN"			: { "compute_mode":1, "shiftday":0 }, 
	"QICE"			: { "compute_mode":1, "shiftday":0 }, 
	"QSNOW"			: { "compute_mode":1, "shiftday":0 }, 
	"QGRAUP"			: { "compute_mode":1, "shiftday":0 }, 
	"Q"			: { "compute_mode":1, "shiftday":0 }, 
	"T"			: { "compute_mode":1, "shiftday":0 }, 
	"U"			: { "compute_mode":1, "shiftday":0 }, 
	"V"			: { "compute_mode":1, "shiftday":0 }, 
	"W"			: { "compute_mode":1, "shiftday":0 }, 
	"QA"		: { "compute_mode":1, "shiftday":0 }, 
	"UA"		: { "compute_mode":1, "shiftday":0 }, 
	"VA"		: { "compute_mode":1, "shiftday":0 }, 
	"TA"		: { "compute_mode":1, "shiftday":0 }, 
	"ALBEDO"	: { "compute_mode":1, "shiftday":0 },
	"XWLIQ"	: { "compute_mode":1, "shiftday":0 },
	"XALB"	: { "compute_mode":1, "shiftday":0 },
	"XALBV"	: { "compute_mode":1, "shiftday":0 },
	"XALBG"	: { "compute_mode":1, "shiftday":0 },
	"XSSUN"	: { "compute_mode":1, "shiftday":0 },
	"XSSHA"	: { "compute_mode":1, "shiftday":0 },
	"XSABG"	: { "compute_mode":1, "shiftday":0 },
	"XSABVG"	: { "compute_mode":1, "shiftday":0 },
	"XSABVSUN"	: { "compute_mode":1, "shiftday":0 },
	"XSABVSHA"	: { "compute_mode":1, "shiftday":0 },
	"TSK"		: { "compute_mode":1, "shiftday":0 },
	"TSLB"		: { "compute_mode":1, "shiftday":0 },
	"SMOIS"		: { "compute_mode":1, "shiftday":0 },
} 
#save seasonal data of following vars:

seasonal_allvars  = (         'PRAVG'     , 'PRMAX'   , 'PRMIN'    , 'RAINC'   , 'RAINNC'  , 
                  'AU10'    , 'AV10'      , 'AQ2M'    , 'WSAVG'    , 'WSMAX'   , 
                  'AT2M'    , 'T2MAX'     , 'T2MIN'   , 
                  'ASWUPT'  , 'ASWUPTC'   , 'ASWDNT'  , 'ASWDNS'   , 'ASWDNSC' , 'ASWUPS'  , 'ASWUPSC' , 
                  'ALWUPT'  , 'ALWUPTC'   , 'ALWDNS'  , 'ALWDNSC'  , 'ALWUPS'  , 'ALWUPSC' , 
                  'TCWPC'   , 'TCWPI'     , 'TCWPR'   , 
                  'CLDFRAg' , 'CLDFRApbl' , 'CLDFRA'  , 'CLDCNVg'  , 'CLDSCUg' , 
                  'EMISS'   , 'QFX'       , 'LH'      , 
                  'XSWI'    , 'PBLH'      , 'TKES'    , 'UST'      , 'WCSTAR'  , 
                  'BR'      , 'POTEVP'    , 'SFROFF'  , 'UDROFF'   , 'SNOW'    , 
                  'SNOWH'   , 'XTSS'      , 'XSMTg'   , 'XOUTFLOW' , 'XPARSUN' , 'XPARSHA' , 
                  'AHFX'    , 'ALFX'      , 'XETR'    , 'XFEVPL'   , 'XFEVPG'  , 'XZWT'    , 
                  'ALBEDO'  , 'TSK'       , 
                  'TSLB'    , 'SMOIS'     , 'XQRCHRG' , 
                  'PS'      , 'PSL'       ,
                  #3D
                  'H'       , 'T'         , 'Q'       , 'U'        , 'V'       , 'W',
                  'QCLOUD'  , 'QRAIN'     , 'QICE'     
				 	)


#save monthly data of following vars:
monthly_allvars  = (           'PRAVG'     , 'PRMAX'   , 'PRMIN'    , 'RAINC'   , 'RAINNC'  , 
                  'AU10'    , 'AV10'      , 'AQ2M'    , 'WSAVG'    , 'WSMAX'   , 
                  'AT2M'    , 'T2MAX'     , 'T2MIN'   , 
                  'ASWUPT'  , 'ASWUPTC'   , 'ASWDNT'  , 'ASWDNS'   , 'ASWDNSC' , 'ASWUPS'  , 'ASWUPSC' , 
                  'ALWUPT'  , 'ALWUPTC'   , 'ALWDNS'  , 'ALWDNSC'  , 'ALWUPS'  , 'ALWUPSC' , 
                  'TCWPC'   , 'TCWPI'     , 'TCWPR'   , 
                  'CLDFRAg' , 'CLDFRApbl' , 'CLDFRA'  , 'CLDCNVg'  , 'CLDSCUg' , 
                  'EMISS'   , 'QFX'       , 'LH'      , 
                  'XSWI'    , 'PBLH'      , 'TKES'    , 'UST'      , 'WCSTAR'  , 
                  'BR'      , 'POTEVP'    , 'SFROFF'  , 'UDROFF'   , 'SNOW'    , 
                  'SNOWH'   , 'XTSS'      , 'XSMTg'   , 'XOUTFLOW' , 'XPARSUN' , 'XPARSHA' , 
                  'AHFX'    , 'ALFX'      , 'XETR'    , 'XFEVPL'   , 'XFEVPG'  , 'XZWT'    , 
                  'ALBEDO'  , 'TSK'       , 
                  'TSLB'    , 'SMOIS'     , 'XQRCHRG' , 
                  'PS'      , 'PSL'       ,
                  #3D
                  'H'       , 'T'         , 'Q'       , 'U'        , 'V'       , 'W',
                  'QCLOUD'  , 'QRAIN'     , 'QICE'     
				 	)

# save daily data of following vars 
daily_allvars    =("PRAVG","AT2M","XTSS","XSMTg","SNOW","SNOWH","UDROFF","XZWT","QFX")
"""
daily_allvars    = (        'W'         , 'PRMAX'   ,   'RAINC'  ,'RAINNC'  ,
                            'AT2M'      , 'T2MAX'   , 'T2MIN'    , 'SFROFF' , 'CLDFRAg' , 
                            'CLDFRApbl' , 'CLDCNVg' , 'CLDSCUg'  , 
                            'TCWPC'     , 'TCWPI'   , 'TCWPR'    , 
                            'TSLB'      , 'SMOIS'   , 'XQRCHRG'  , 
                            'XTSS'      ,'XSMTg'    ,'SNOW'      ,'SNOWH'   ,'UDROFF'   ,'XZWT'   ,'QFX',
                            'UQg'       , 'VQg'     , 'XOUTFLOW' , 'XRBAS'  , 'XRDRN'   , 'XRSAT' , 
                            'UDROFF'
				 	)
"""

# diurnal cycle vars:
diurnal_allvars  = (       'PRAVG','RAINC'   ,'RAINNC'  ,
                       'AT2M'    , 'T2MAX'     , 'T2MIN'   , 
                       'AU10'    , 'AV10'      , 'AQ2M'    , 
                       'TCWPC'   , 'TCWPI'     , 
                       'CLDFRAg' , 'CLDFRApbl' , 'CLDCNVg' , 'CLDSCUg' , 
                       'XSWI'    , 'PBLH'      , 'TKES'    , 'UST'     , 'WCSTAR' , 
                       'BR'      , 'SNOW'      , 
                       'SNOWH'   , 'XTSS'      , 'XSMTg'   , 'XPARSUN' , 
                       'XPARSHA' , 'AHFX'      , 'ALFX'    , 'XETR'    , 'XFEVPL' , 
                       'XFEVPG'  , 'XZWT'      , 'ALBEDO'  , 'TSK'
				 	)


# hourly vars:
hourly_allvars  = ('PRAVG' , 'H'      , 'T'     , 'U'    , 'V' , 'W' , 
                        'Q', 'QCLOUD' , 'QRAIN' , 'QICE'
				 	)
postList={"seasonal":seasonal_allvars,"monthly":monthly_allvars,"daily":daily_allvars,"diurnal":diurnal_allvars} #,
      #  "3hourly":hourly3_allvars}
